# Generated by Django 5.1.7 on 2025-05-23 13:59

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InventoryTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("ADD", "Add to Total"),
                            ("ACTIVATE", "Move to Available"),
                            ("ESCROW", "Place in Escrow"),
                            ("COMPLETE", "Complete Transaction"),
                            ("CANCEL", "Cancel Escrow"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("previous_total", models.IntegerField()),
                ("previous_available", models.IntegerField()),
                ("previous_in_escrow", models.IntegerField()),
                ("new_total", models.IntegerField()),
                ("new_available", models.IntegerField()),
                ("new_in_escrow", models.IntegerField()),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Inventory Transaction",
                "db_table": "inventory_transaction",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NegotiationHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("price_offered", "Price Offered"),
                            ("price_accepted", "Price Accepted"),
                            ("price_rejected", "Price Rejected"),
                            ("price_countered", "Price Countered"),
                            ("price_updated", "Price Updated"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Negotiation histories",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="PriceNegotiation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "original_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("offered_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "final_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("countered", "Countered"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("offered_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "original_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("is_active", models.BooleanField(default=True)),
                ("total_inventory", models.IntegerField(default=0)),
                ("available_inventory", models.IntegerField(default=0)),
                ("in_escrow_inventory", models.IntegerField(default=0)),
                ("negotiable", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("INACTIVE", "Inactive"),
                        ],
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("specifications", models.JSONField(blank=True, default=dict)),
                ("slug", models.SlugField(blank=True, max_length=255)),
                (
                    "short_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=200,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Products",
                "db_table": "products",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductCondition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name_plural": "Product Conditions",
                "db_table": "product_conditions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="product_images/")),
                ("is_primary", models.BooleanField(default=False)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Product Images",
                "db_table": "product_images",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="ProductMeta",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("featured", models.BooleanField(default=False)),
                ("total_shares", models.PositiveIntegerField(default=0)),
                ("seo_keywords", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name_plural": "Product Meta",
                "db_table": "product_meta",
                "ordering": ["-views_count"],
            },
        ),
        migrations.CreateModel(
            name="ProductWatchlistItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "product_watchlist_items",
            },
        ),
    ]
