# Generated by Django 5.1.7 on 2025-06-02 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        ("products", "0001_initial"),
        ("transactions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorytransaction",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="negotiationhistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="pricenegotiation",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="negotiations_as_buyer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pricenegotiation",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="negotiations_as_seller",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pricenegotiation",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="negotiations",
                to="transactions.escrowtransaction",
            ),
        ),
        migrations.AddField(
            model_name="negotiationhistory",
            name="negotiation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="products.pricenegotiation",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="categories.category"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pricenegotiation",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="negotiations",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="inventorytransaction",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_transactions",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="condition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="products.productcondition",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="productmeta",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meta",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="productrating",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="productrating",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="productratingaggregate",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rating_aggregate",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="options",
            field=models.ManyToManyField(
                related_name="variants", to="products.productvariantoption"
            ),
        ),
        migrations.AddIndex(
            model_name="productvarianttype",
            index=models.Index(
                fields=["is_active", "sort_order"],
                name="products_pr_is_acti_3c9519_idx",
            ),
        ),
        migrations.AddField(
            model_name="productvariantoption",
            name="variant_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="products.productvarianttype",
            ),
        ),
        migrations.AddField(
            model_name="productwatchlistitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watchers",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="productwatchlistitem",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watchlist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ratinghelpfulness",
            name="rating",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="helpfulness_votes",
                to="products.productrating",
            ),
        ),
        migrations.AddField(
            model_name="ratinghelpfulness",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(
                fields=["transaction_type"], name="inventory_t_transac_bd472b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["slug"], name="products_slug_5e91f2_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["short_code"], name="products_short_c_9d2269_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("slug", "short_code")},
        ),
        migrations.AddIndex(
            model_name="productrating",
            index=models.Index(
                fields=["product", "is_approved", "-created_at"],
                name="products_pr_product_22f9e5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productrating",
            index=models.Index(
                fields=["rating", "is_approved"], name="products_pr_rating_c76416_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productrating",
            index=models.Index(
                fields=["is_verified_purchase", "is_approved"],
                name="products_pr_is_veri_4bfcd1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productrating",
            index=models.Index(
                fields=["-helpful_count", "is_approved"],
                name="products_pr_helpful_cfb91a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productrating",
            unique_together={("product", "user")},
        ),
        migrations.AddIndex(
            model_name="productratingaggregate",
            index=models.Index(
                fields=["-average_rating", "total_count"],
                name="products_pr_average_9af195_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["product", "is_active"], name="products_pr_product_66459e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(fields=["sku"], name="products_pr_sku_dcab68_idx"),
        ),
        migrations.AddIndex(
            model_name="productvariantoption",
            index=models.Index(
                fields=["variant_type", "is_active", "sort_order"],
                name="products_pr_variant_28fcc2_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productvariantoption",
            unique_together={("variant_type", "value")},
        ),
        migrations.AddIndex(
            model_name="productwatchlistitem",
            index=models.Index(
                fields=["user", "product"], name="product_wat_user_id_1f2ebc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productwatchlistitem",
            index=models.Index(
                fields=["product", "added_at"], name="product_wat_product_ebac0b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productwatchlistitem",
            index=models.Index(
                fields=["added_at"], name="product_wat_added_a_fa74b7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productwatchlistitem",
            unique_together={("user", "product")},
        ),
        migrations.AlterUniqueTogether(
            name="ratinghelpfulness",
            unique_together={("rating", "user")},
        ),
    ]
