# Generated by Django 5.1.7 on 2025-05-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="short_code",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, null=True, unique=True
            ),
        ),
    ]
