# Generated by Django 5.1.7 on 2025-05-08 21:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventorytransaction",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "Inventory Transaction",
            },
        ),
        migrations.AddField(
            model_name="inventorytransaction",
            name="new_available",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inventorytransaction",
            name="new_in_escrow",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inventorytransaction",
            name="new_total",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inventorytransaction",
            name="previous_available",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inventorytransaction",
            name="previous_in_escrow",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inventorytransaction",
            name="previous_total",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inventorytransaction",
            name="quantity",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("ADD", "Add to Total"),
                    ("ACTIVATE", "Move to Available"),
                    ("ESCROW", "Place in Escrow"),
                    ("COMPLETE", "Complete Transaction"),
                    ("CANCEL", "Cancel Escrow"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(
                fields=["transaction_type"], name="inventory_t_transac_bd472b_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="inventorytransaction",
            table="inventory_transaction",
        ),
    ]
