# Generated by Django 5.1.7 on 2025-04-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_category_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
    ]
