# Generated by Django 5.1.7 on 2025-06-07 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product_watchlist", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="productwatchlistitem",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watchlist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="productwatchlistitem",
            index=models.Index(
                fields=["user", "product"], name="product_wat_user_id_794b64_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productwatchlistitem",
            index=models.Index(
                fields=["product", "added_at"], name="product_wat_product_854b34_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productwatchlistitem",
            index=models.Index(
                fields=["added_at"], name="product_wat_added_a_536dd9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productwatchlistitem",
            unique_together={("user", "product")},
        ),
    ]
