# Generated by Django 5.1.7 on 2025-06-04 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("store", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userstore",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="store",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="userstore",
            index=models.Index(fields=["slug"], name="user_stores_slug_21a148_idx"),
        ),
        migrations.AddConstraint(
            model_name="userstore",
            constraint=models.UniqueConstraint(
                fields=("user", "slug"), name="unique_user_store"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userstore",
            unique_together={("user", "slug")},
        ),
    ]
