# Generated by Django 5.1.7 on 2025-06-04 21:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product_base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImageVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("quality", models.PositiveIntegerField(default=85)),
                ("is_active", models.BooleanField(default=True)),
                ("created_by_admin", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "product_image_variants",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image_url", models.URLField()),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_by_user", models.BooleanField(default=False)),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("file_size", models.PositiveIntegerField(default=0)),
                ("width", models.PositiveIntegerField(default=0)),
                ("height", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="product_base.product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="images",
                        to="product_image.productimagevariant",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Product Images",
                "db_table": "product_product_images",
                "ordering": ["display_order"],
                "indexes": [
                    models.Index(
                        fields=["product", "is_primary"],
                        name="product_pro_product_7e97cb_idx",
                    ),
                    models.Index(
                        fields=["product", "variant", "display_order"],
                        name="product_pro_product_0e1e22_idx",
                    ),
                    models.Index(
                        fields=["is_active", "product"],
                        name="product_pro_is_acti_aa6ebe_idx",
                    ),
                ],
            },
        ),
    ]
