# Generated by Django 5.1.7 on 2025-06-07 10:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BrandVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("language_code", models.CharField(max_length=10)),
                ("region_code", models.CharField(blank=True, max_length=10)),
                ("description", models.TextField(blank=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="brands/variants/"
                    ),
                ),
                ("local_website", models.URLField(blank=True)),
                ("local_contact_email", models.EmailField(blank=True, max_length=254)),
                ("local_social_media", models.JSONField(blank=True, default=dict)),
                ("is_auto_generated", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "product_brand_variants",
            },
        ),
        migrations.CreateModel(
            name="BrandVariantTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("language_code", models.CharField(max_length=10)),
                ("region_code", models.CharField(blank=True, max_length=10)),
                (
                    "name_translations",
                    models.JSONField(
                        default=dict,
                        help_text="Common brand name translations for this locale",
                    ),
                ),
                ("default_settings", models.JSONField(default=dict)),
                ("auto_generate_for_brands", models.BooleanField(default=False)),
                (
                    "brand_criteria",
                    models.JSONField(
                        default=dict,
                        help_text="Criteria for auto-generating (e.g., min_products, countries)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "product_brand_variant_templates",
            },
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="brands/logos/"),
                ),
                ("website", models.URLField(blank=True)),
                (
                    "founded_year",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "country_of_origin",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                ("is_verified", models.BooleanField(db_index=True, default=False)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("social_media", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("cached_product_count", models.PositiveIntegerField(default=0)),
                (
                    "cached_average_rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("stats_updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Brands",
                "db_table": "product_brands",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "is_featured"],
                        name="product_bra_is_acti_7e3afa_idx",
                    ),
                    models.Index(
                        fields=["is_active", "is_verified"],
                        name="product_bra_is_acti_ab3dab_idx",
                    ),
                    models.Index(
                        fields=["country_of_origin", "is_active"],
                        name="product_bra_country_da0e7a_idx",
                    ),
                    models.Index(
                        fields=["founded_year", "is_active"],
                        name="product_bra_founded_96a0c4_idx",
                    ),
                    models.Index(
                        fields=["name", "country_of_origin"],
                        name="product_bra_name_b9afa5_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BrandRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("brand_name", models.CharField(max_length=100)),
                (
                    "reason",
                    models.TextField(help_text="Why should this brand be added?"),
                ),
                ("website", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                (
                    "created_brand",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="brand_request",
                        to="product_brand.brand",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Brand Requests",
                "db_table": "product_brand_requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
