# Generated by Django 5.1.7 on 2025-06-04 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product_brand", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="brandrequest",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_brand_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="brandrequest",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brand_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="brandvariant",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="product_brand.brand",
            ),
        ),
        migrations.AddField(
            model_name="brandvariant",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="brandvariant",
            index=models.Index(
                fields=["brand", "language_code"], name="product_bra_brand_i_e52ffa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="brandvariant",
            index=models.Index(
                fields=["language_code", "region_code"],
                name="product_bra_languag_2301fa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="brandvariant",
            index=models.Index(
                fields=["is_active"], name="product_bra_is_acti_04dbfb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="brandvariant",
            unique_together={("brand", "language_code", "region_code")},
        ),
    ]
