# Generated by Django 5.1.7 on 2025-07-17 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_brand", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandvariant",
            name="template",
            field=models.ForeignKey(
                blank=True,
                help_text="Template used to generate this variant",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="variants",
                to="product_brand.brandvarianttemplate",
            ),
        ),
    ]
