# Generated by Django 5.1.7 on 2025-07-09 08:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(unique=True)),
                ("total_searches", models.PositiveIntegerField(default=0)),
                ("unique_users", models.PositiveIntegerField(default=0)),
                ("avg_response_time", models.FloatField(default=0.0)),
                ("top_queries", models.JSONField(blank=True, default=list)),
            ],
            options={
                "db_table": "search_analytics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="PopularSearch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("query", models.CharField(max_length=255, unique=True)),
                ("search_count", models.PositiveIntegerField(default=0)),
                ("last_searched", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "popular_search",
                "ordering": ["-search_count", "-last_searched"],
                "indexes": [
                    models.Index(fields=["query"], name="popular_sea_query_4e7f38_idx"),
                    models.Index(
                        fields=["search_count"], name="popular_sea_search__07e817_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SearchLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("query", models.CharField(max_length=255)),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("results_count", models.PositiveIntegerField(default=0)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("response_time", models.FloatField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "search_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["query"], name="search_log_query_8d8a06_idx"),
                    models.Index(
                        fields=["created_at"], name="search_log_created_8af1bc_idx"
                    ),
                    models.Index(fields=["user"], name="search_log_user_id_cbb5fb_idx"),
                ],
            },
        ),
    ]
