# Generated by Django 5.1.7 on 2025-06-04 21:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product_base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductMeta",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("featured", models.BooleanField(default=False)),
                ("total_shares", models.PositiveIntegerField(default=0)),
                ("seo_keywords", models.CharField(blank=True, max_length=255)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meta",
                        to="product_base.product",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Product Meta",
                "db_table": "product_meta",
                "ordering": ["-views_count"],
            },
        ),
    ]
