# Generated by Django 5.1.7 on 2025-06-15 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_metadata", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productmeta",
            options={
                "ordering": ["-views_count"],
                "verbose_name": "Product Meta",
                "verbose_name_plural": "Product Meta",
            },
        ),
        migrations.RemoveField(
            model_name="productmeta",
            name="featured",
        ),
        migrations.AlterModelTable(
            name="productmeta",
            table="product_metadata",
        ),
    ]
