# Generated by Django 5.1.7 on 2025-06-17 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_metadata", "0002_alter_productmeta_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productmeta",
            name="total_shares",
        ),
    ]
