# Generated by Django 5.1.7 on 2025-06-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_metadata", "0003_remove_productmeta_total_shares"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmeta",
            name="seo_generation_queued",
            field=models.BooleanField(default=False),
        ),
    ]
