# Generated by Django 5.1.7 on 2025-06-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_metadata", "0004_productmeta_seo_generation_queued"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmeta",
            name="seo_keywords",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
