# Generated by Django 5.1.7 on 2025-07-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_metadata", "0006_alter_productmeta_seo_keywords"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmeta",
            name="seo_keywords",
            field=models.JSONField(
                blank=True, help_text="SEO keywords for the product", null=True
            ),
        ),
    ]
