# Generated by Django 5.1.7 on 2025-07-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_metadata", "0007_alter_productmeta_seo_keywords"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmeta",
            name="seo_keywords",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="SEO keywords for the product",
                null=True,
            ),
        ),
    ]
