# Generated by Django 5.1.7 on 2025-06-08 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_detail", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="productdetail",
            new_name="product_det_product_70d87a_idx",
            old_name="product_pro_product_87df0d_idx",
        ),
        migrations.RenameIndex(
            model_name="productdetail",
            new_name="product_det_product_aa488c_idx",
            old_name="product_pro_product_d5fec3_idx",
        ),
        migrations.RenameIndex(
            model_name="productdetail",
            new_name="product_det_product_310c6c_idx",
            old_name="product_pro_product_79414b_idx",
        ),
        migrations.RenameIndex(
            model_name="productdetail",
            new_name="product_det_detail__54abc0_idx",
            old_name="product_pro_detail__2ce083_idx",
        ),
        migrations.RenameIndex(
            model_name="productdetail",
            new_name="product_det_product_ef779a_idx",
            old_name="product_pro_product_466467_idx",
        ),
        migrations.RenameIndex(
            model_name="productdetail",
            new_name="product_det_templat_abaad7_idx",
            old_name="product_pro_templat_7233f6_idx",
        ),
        migrations.AlterUniqueTogether(
            name="productdetailtemplate",
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name="productdetail",
            table="product_details",
        ),
    ]
