# Generated by Django 5.1.7 on 2025-06-08 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
        (
            "product_detail",
            "0002_rename_product_pro_product_87df0d_idx_product_det_product_70d87a_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productdetailtemplate",
            unique_together={("label", "category")},
        ),
    ]
