# Generated by Django 5.1.7 on 2025-06-08 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_detail", "0003_alter_productdetailtemplate_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productdetail",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="productdetailtemplate",
            unique_together=set(),
        ),
    ]
