# Generated by Django 5.1.7 on 2025-06-08 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "product_detail",
            "0005_rename_product_det_product_70d87a_idx_product_pro_product_87df0d_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productdetail",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="productdetailtemplate",
            unique_together=set(),
        ),
    ]
