# Generated by Django 5.1.7 on 2025-06-07 10:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product_base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVariantType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                "db_table": "product_variant_type",
                "ordering": ["sort_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "sort_order"],
                        name="product_var_is_acti_8a48e2_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductVariantOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("value", models.CharField(db_index=True, max_length=100)),
                ("slug", models.SlugField()),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "variant_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="product_variant.productvarianttype",
                    ),
                ),
            ],
            options={
                "db_table": "product_variant_option",
                "ordering": ["sort_order", "value"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sku", models.CharField(db_index=True, max_length=100, unique=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("stock_quantity", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="product_base.product",
                    ),
                ),
                (
                    "options",
                    models.ManyToManyField(
                        related_name="variants",
                        to="product_variant.productvariantoption",
                    ),
                ),
            ],
            options={
                "db_table": "product_variant",
                "indexes": [
                    models.Index(
                        fields=["product", "is_active"],
                        name="product_var_product_fe1f7f_idx",
                    ),
                    models.Index(fields=["sku"], name="product_var_sku_3f6862_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="productvariantoption",
            index=models.Index(
                fields=["variant_type", "is_active", "sort_order"],
                name="product_var_variant_4508af_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productvariantoption",
            unique_together={("variant_type", "value")},
        ),
    ]
