# Generated by Django 4.2.7
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("product_variant", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS 
            idx_variant_option_type_sort_value ON product_variant_option(variant_type_id, sort_order, value);
            """,
            reverse_sql="DROP INDEX IF EXISTS idx_variant_option_type_sort_value;",
        ),
    ]
