# Generated by Django 5.1.7 on 2025-06-21 05:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_base", "0008_alter_product_slug"),
        ("product_variant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVariantImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="variant_images/")),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_primary", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "product_variant_image",
                "ordering": ["sort_order"],
            },
        ),
        migrations.AddField(
            model_name="productvariant",
            name="cost_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Cost to acquire/produce this variant",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="dimensions_height",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Height in cm",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="dimensions_length",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Length in cm",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="dimensions_width",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Width in cm",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="escrow_hold_period",
            field=models.PositiveIntegerField(
                default=7,
                help_text="Days to hold payment in escrow after delivery confirmation",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="expected_restock_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="is_backorderable",
            field=models.BooleanField(
                default=False, help_text="Can be ordered when out of stock"
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="is_digital",
            field=models.BooleanField(
                default=False, help_text="Whether this is a digital product"
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="low_stock_threshold",
            field=models.PositiveIntegerField(
                default=5, help_text="Alert when stock falls below this level"
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="requires_inspection",
            field=models.BooleanField(
                default=False,
                help_text="Whether this variant requires inspection before escrow release",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="requires_shipping",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="reserved_quantity",
            field=models.PositiveIntegerField(
                default=0, help_text="Quantity reserved for pending orders"
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Weight in kg",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="productvariantoption",
            name="color_code",
            field=models.CharField(
                blank=True, help_text="Hex color code for color swatches", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="productvariantoption",
            name="display_value",
            field=models.CharField(
                blank=True,
                help_text="Display name if different from value",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="productvariantoption",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="variant_options/"
            ),
        ),
        migrations.AddField(
            model_name="productvariantoption",
            name="price_adjustment",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Price adjustment for this option (can be negative)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="productvarianttype",
            name="affects_inventory",
            field=models.BooleanField(
                default=True,
                help_text="Whether this variant type affects inventory tracking",
            ),
        ),
        migrations.AddField(
            model_name="productvarianttype",
            name="affects_price",
            field=models.BooleanField(
                default=False, help_text="Whether this variant type can affect pricing"
            ),
        ),
        migrations.AddField(
            model_name="productvarianttype",
            name="display_type",
            field=models.CharField(
                choices=[
                    ("dropdown", "Dropdown"),
                    ("radio", "Radio Buttons"),
                    ("color_swatch", "Color Swatch"),
                    ("image_swatch", "Image Swatch"),
                    ("text", "Text Input"),
                ],
                default="dropdown",
                help_text="How this variant should be displayed to customers",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="productvarianttype",
            name="is_required",
            field=models.BooleanField(
                default=True,
                help_text="Whether this variant type is required for all products",
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["stock_quantity"], name="product_var_stock_q_e83d15_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["is_active", "stock_quantity"],
                name="product_var_is_acti_6eb16e_idx",
            ),
        ),
        migrations.AddField(
            model_name="productvariantimage",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="product_variant.productvariant",
            ),
        ),
        migrations.AddIndex(
            model_name="productvariantimage",
            index=models.Index(
                fields=["variant", "sort_order"], name="product_var_variant_029953_idx"
            ),
        ),
    ]
