# Generated by Django 4.2.7
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("product_variant", "0002_add_variant_option_indexes"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Optimize variant type lookups
            CREATE INDEX IF NOT EXISTS idx_variant_type_lookup 
            ON product_variant_type(id, name, is_active);

            -- Optimize variant options lookups
            CREATE INDEX IF NOT EXISTS idx_variant_options_lookup 
            ON product_variant_option(variant_type_id, sort_order, value);

            -- Optimize product variant lookups
            CREATE INDEX IF NOT EXISTS idx_product_variant_lookup 
            ON product_variant(product_id, id);

            -- Optimize variant image lookups
            CREATE INDEX IF NOT EXISTS idx_variant_image_lookup 
            ON product_variant_image(variant_id, sort_order);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS idx_variant_type_lookup;
            DROP INDEX IF EXISTS idx_variant_options_lookup;
            DROP INDEX IF EXISTS idx_product_variant_lookup;
            DROP INDEX IF EXISTS idx_variant_image_lookup;
            """,
        ),
    ]
