# Generated by Django 5.1.7 on 2025-06-24 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_base", "0009_remove_product_available_inventory_and_more"),
        (
            "product_variant",
            "0002_productvariantimage_productvariant_cost_price_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="productvariant",
            name="product_var_stock_q_e83d15_idx",
        ),
        migrations.RemoveIndex(
            model_name="productvariant",
            name="product_var_is_acti_6eb16e_idx",
        ),
        migrations.RenameField(
            model_name="productvariant",
            old_name="reserved_quantity",
            new_name="in_escrow_inventory",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="stock_quantity",
        ),
        migrations.AddField(
            model_name="productvariant",
            name="available_inventory",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="pending_inspection",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="rejected_inventory",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="total_inventory",
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["total_inventory"], name="product_var_total_i_d89fb4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["is_active", "total_inventory"],
                name="product_var_is_acti_57b370_idx",
            ),
        ),
    ]
