# Generated by Django 5.1.7 on 2025-06-24 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "product_variant",
            "0003_remove_productvariant_product_var_stock_q_e83d15_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariant",
            name="escrow_hold_period",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="requires_inspection",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="requires_shipping",
        ),
    ]
