# Generated by Django 5.1.7 on 2025-07-21 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_variant", "0003_optimize_variant_indexes"),
        ("product_variant", "0005_alter_productvariantoption_color_code"),
    ]

    operations = []
