# Generated by Django 5.1.7 on 2025-05-05 11:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dispute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("not_as_described", "Item Not As Described"),
                            ("not_received", "Item Not Received"),
                            ("damaged", "Item Damaged"),
                            ("wrong_item", "Wrong Item Received"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("opened", "Opened"),
                            ("in_review", "In Review"),
                            ("resolved_buyer", "Resolved for Buyer"),
                            ("resolved_seller", "Resolved for Seller"),
                            ("closed", "Closed"),
                        ],
                        default="opened",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispute",
                "verbose_name_plural": "Disputes",
                "db_table": "disputes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EscrowTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("payment_received", "Payment Received"),
                            ("shipped", "Item Shipped"),
                            ("delivered", "Item Delivered"),
                            ("inspection", "In Inspection Period"),
                            ("completed", "Completed"),
                            ("disputed", "Disputed"),
                            ("refunded", "Refunded"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="initiated",
                        max_length=20,
                    ),
                ),
                ("inspection_period_days", models.PositiveSmallIntegerField(default=3)),
                ("inspection_end_date", models.DateTimeField(blank=True, null=True)),
                ("tracking_number", models.CharField(blank=True, max_length=100)),
                ("shipping_carrier", models.CharField(blank=True, max_length=100)),
                ("shipping_address", models.JSONField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Escrow Transaction",
                "verbose_name_plural": "Escrow Transactions",
                "db_table": "escrow_transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransactionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("payment_received", "Payment Received"),
                            ("shipped", "Item Shipped"),
                            ("delivered", "Item Delivered"),
                            ("inspection", "In Inspection Period"),
                            ("completed", "Completed"),
                            ("disputed", "Disputed"),
                            ("refunded", "Refunded"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Transaction History",
                "verbose_name_plural": "Transaction Histories",
                "db_table": "transaction_history",
                "ordering": ["-timestamp"],
            },
        ),
    ]
