# Generated by Django 5.1.7 on 2025-05-23 13:59

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EscrowTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("payment_received", "Payment Received"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("inspection", "In Inspection"),
                            ("disputed", "Disputed"),
                            ("completed", "Completed"),
                            ("refunded", "Refunded"),
                            ("cancelled", "Cancelled"),
                            ("funds_released", "Funds Released"),
                        ],
                        default="initiated",
                        max_length=20,
                    ),
                ),
                (
                    "tracking_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "shipping_carrier",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("shipping_address", models.TextField(blank=True, null=True)),
                ("inspection_period_days", models.PositiveSmallIntegerField(default=3)),
                ("inspection_end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "price_by_negotiation",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_auto_transition_scheduled", models.BooleanField(default=False)),
                (
                    "auto_transition_type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "next_auto_transition_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Escrow Transaction",
                "verbose_name_plural": "Escrow Transactions",
                "db_table": "escrow_transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransactionHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("payment_received", "Payment Received"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("inspection", "In Inspection"),
                            ("disputed", "Disputed"),
                            ("completed", "Completed"),
                            ("refunded", "Refunded"),
                            ("cancelled", "Cancelled"),
                            ("funds_released", "Funds Released"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Transaction History",
                "verbose_name_plural": "Transaction Histories",
                "db_table": "transaction_history",
                "ordering": ["-timestamp"],
            },
        ),
    ]
