# Generated by Django 5.1.7 on 2025-04-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="escrowtransaction",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="escrowtransaction",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="escrowtransaction",
            name="shipping_address",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
