# Generated by Django 5.1.7 on 2025-06-11 14:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_base", "0004_initial"),
        ("transactions", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="escrowtransaction",
            index=models.Index(
                fields=["tracking_id"], name="escrow_tran_trackin_28262c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="escrowtransaction",
            index=models.Index(
                fields=["status", "created_at"], name="escrow_tran_status_b2af67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="escrowtransaction",
            index=models.Index(
                fields=["buyer", "status"], name="escrow_tran_buyer_i_ccccf2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="escrowtransaction",
            index=models.Index(
                fields=["seller", "status"], name="escrow_tran_seller__ec102a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="escrowtransaction",
            index=models.Index(
                fields=["created_at", "status"], name="escrow_tran_created_53c5aa_idx"
            ),
        ),
    ]
