# Generated by Django 5.1.7 on 2025-05-09 15:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="escrowtransaction",
            name="auto_transition_type",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="escrowtransaction",
            name="is_auto_transition_scheduled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="escrowtransaction",
            name="next_auto_transition_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="escrowtransaction",
            name="status_changed_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="escrowtransaction",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name="escrowtransaction",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="buyer_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="escrowtransaction",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="seller_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="escrowtransaction",
            name="shipping_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="escrowtransaction",
            name="shipping_carrier",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="escrowtransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("initiated", "Initiated"),
                    ("payment_received", "Payment Received"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("inspection", "In Inspection"),
                    ("disputed", "Disputed"),
                    ("completed", "Completed"),
                    ("refunded", "Refunded"),
                    ("cancelled", "Cancelled"),
                ],
                default="initiated",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="escrowtransaction",
            name="tracking_id",
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="escrowtransaction",
            name="tracking_number",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transactionhistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("initiated", "Initiated"),
                    ("payment_received", "Payment Received"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("inspection", "In Inspection"),
                    ("disputed", "Disputed"),
                    ("completed", "Completed"),
                    ("refunded", "Refunded"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=20,
            ),
        ),
    ]
