# Generated by Django 5.1.7 on 2025-05-03 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_transactionhistory_dispute"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transactionhistory",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Transaction History",
                "verbose_name_plural": "Transaction Histories",
            },
        ),
        migrations.AlterUniqueTogether(
            name="transactionhistory",
            unique_together={("transaction", "timestamp")},
        ),
        migrations.AlterModelTable(
            name="transactionhistory",
            table="transaction_history",
        ),
    ]
