# Generated by Django 5.1.7 on 2025-06-12 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_base", "0004_initial"),
        (
            "transactions",
            "0003_escrowtransaction_escrow_tran_trackin_28262c_idx_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="transactionhistory",
            old_name="status",
            new_name="new_status",
        ),
        migrations.AddField(
            model_name="transactionhistory",
            name="previous_status",
            field=models.CharField(
                choices=[
                    ("initiated", "Initiated"),
                    ("payment_received", "Payment Received"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("inspection", "In Inspection"),
                    ("disputed", "Disputed"),
                    ("completed", "Completed"),
                    ("refunded", "Refunded"),
                    ("cancelled", "Cancelled"),
                    ("funds_released", "Funds Released"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="escrowtransaction",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="escrow_transactions",
                to="product_base.product",
            ),
        ),
    ]
