# Generated by Django 5.1.7 on 2025-05-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_escrowtransaction_auto_transition_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="escrowtransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("initiated", "Initiated"),
                    ("payment_received", "Payment Received"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("inspection", "In Inspection"),
                    ("disputed", "Disputed"),
                    ("completed", "Completed"),
                    ("refunded", "Refunded"),
                    ("cancelled", "Cancelled"),
                    ("funds_released", "Funds Released"),
                ],
                default="initiated",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transactionhistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("initiated", "Initiated"),
                    ("payment_received", "Payment Received"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("inspection", "In Inspection"),
                    ("disputed", "Disputed"),
                    ("completed", "Completed"),
                    ("refunded", "Refunded"),
                    ("cancelled", "Cancelled"),
                    ("funds_released", "Funds Released"),
                ],
                max_length=20,
            ),
        ),
    ]
