# Generated by Django 5.1.7 on 2025-06-13 21:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0004_rename_status_transactionhistory_new_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EscrowTimeout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "timeout_type",
                    models.CharField(
                        choices=[
                            ("shipping", "Shipping Timeout"),
                            ("inspection_start", "Auto Inspection"),
                            ("inspection_end", "Auto Completion"),
                            ("dispute_refund", "Auto Refund"),
                        ],
                        help_text="Type of automatic transition being scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        help_text="Status the transaction should be in when timeout executes",
                        max_length=20,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        help_text="Status to transition to when timeout expires",
                        max_length=20,
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this timeout was scheduled",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When the automatic transition should occur"
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        help_text="Celery task ID for cancellation purposes",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "is_executed",
                    models.BooleanField(
                        default=False, help_text="Whether the timeout has been executed"
                    ),
                ),
                (
                    "is_cancelled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the timeout was cancelled (due to manual status change)",
                    ),
                ),
                (
                    "execution_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes about timeout execution or cancellation",
                    ),
                ),
                (
                    "executed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the timeout was actually executed",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeouts",
                        to="transactions.escrowtransaction",
                    ),
                ),
            ],
            options={
                "db_table": "escrow_timeouts",
                "indexes": [
                    models.Index(
                        fields=["transaction", "timeout_type"],
                        name="escrow_time_transac_b1128d_idx",
                    ),
                    models.Index(
                        fields=["expires_at", "is_executed", "is_cancelled"],
                        name="escrow_time_expires_d20036_idx",
                    ),
                    models.Index(
                        fields=["celery_task_id"], name="escrow_time_celery__2c6f9d_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("is_cancelled", False), ("is_executed", False)
                        ),
                        fields=("transaction", "timeout_type"),
                        name="unique_active_timeout_per_type",
                    )
                ],
            },
        ),
    ]
