# Generated by Django 5.1.7 on 2025-05-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0004_alter_escrowtransaction_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="escrowtransaction",
            name="price_by_negotiation",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
