# Generated by Django 5.1.7 on 2025-06-14 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0005_escrowtimeout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="escrowtimeout",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="escrowtimeout",
                to="transactions.escrowtransaction",
            ),
        ),
    ]
