# Generated by Django 5.1.7 on 2025-06-22 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "product_variant",
            "0002_productvariantimage_productvariant_cost_price_and_more",
        ),
        ("transactions", "0007_remove_escrowtransaction_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="escrowtransaction",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="escrowtransaction",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="escrow_transactions",
                to="product_variant.productvariant",
            ),
        ),
    ]
