# Generated by Django 5.1.7 on 2025-06-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0008_escrowtransaction_total_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="escrowtransaction",
            name="selected_options",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
