# Generated by Django 5.1.7 on 2025-07-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0009_escrowtransaction_selected_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="escrowtransaction",
            name="rating_setup_done",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="escrowtransaction",
            name="rating_setup_done_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
