# Generated by Django 5.1.7 on 2025-07-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0010_escrowtransaction_rating_setup_done_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="escrowtransaction",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="low",
                max_length=20,
            ),
        ),
    ]
