# Generated by Django 5.1.7 on 2025-07-12 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0011_escrowtransaction_priority"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="escrowtransaction",
            name="priority",
        ),
    ]
