# Generated by Django 5.1.7 on 2026-07-18 14:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0012_remove_escrowtransaction_priority"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FundHold",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="The amount held", max_digits=12
                    ),
                ),
                (
                    "hold_type",
                    models.CharField(
                        choices=[
                            ("transaction_hold", "Transaction Hold"),
                            ("dispute_hold", "Dispute Hold"),
                            ("reserve_hold", "Reserve Hold"),
                        ],
                        default="transaction_hold",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("released", "Released"),
                            ("voided", "Voided"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Explanation of why the hold was created"
                    ),
                ),
                (
                    "released_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this hold was released/voided",
                        null=True,
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        help_text="The seller whose funds are held",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funds_holds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        help_text="The transaction this hold is tied to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holds",
                        to="transactions.escrowtransaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fund Hold",
                "verbose_name_plural": "Fund Holds",
                "db_table": "escrow_funds_holds",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["seller", "status"],
                        name="escrow_fund_seller__eeca64_idx",
                    ),
                    models.Index(
                        fields=["transaction", "status"],
                        name="escrow_fund_transac_08a69e_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SellerBalanceLedger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The transaction amount (positive for credits, negative for debits)",
                        max_digits=12,
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("sale_credit", "Sale Credit"),
                            ("payout_debit", "Payout Debit"),
                            ("platform_fee", "Platform Fee"),
                            ("refund_debit", "Refund Debit"),
                            ("chargeback_debit", "Chargeback Debit"),
                            ("adjustment", "Balance Adjustment"),
                        ],
                        default="sale_credit",
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Explanation of the ledger adjustment"
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        help_text="The seller account this entry relates to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        help_text="The related transaction (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_entries",
                        to="transactions.escrowtransaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seller Balance Ledger Entry",
                "verbose_name_plural": "Seller Balance Ledger Entries",
                "db_table": "seller_balance_ledger",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["seller", "created_at"],
                        name="seller_bala_seller__390e72_idx",
                    ),
                    models.Index(
                        fields=["entry_type"], name="seller_bala_entry_t_4aa6b7_idx"
                    ),
                ],
            },
        ),
    ]
