# Generated by Django 5.1.7 on 2025-07-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0002_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userrating",
            name="unique_rating",
        ),
        migrations.AlterUniqueTogether(
            name="userrating",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="userrating",
            name="can_rate_from",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userrating",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userrating",
            name="rating_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name="userrating",
            table=None,
        ),
    ]
