# Generated by Django 5.1.7 on 2025-07-02 22:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0003_remove_userrating_unique_rating_and_more"),
        ("transactions", "0009_escrowtransaction_selected_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userrating",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "User Rating",
                "verbose_name_plural": "User Ratings",
            },
        ),
        migrations.AlterUniqueTogether(
            name="userrating",
            unique_together={("transaction", "from_user", "to_user")},
        ),
        migrations.AlterModelTable(
            name="userrating",
            table="user_ratings",
        ),
    ]
