# Generated by Django 5.1.7 on 2025-07-03 14:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0005_ratingeligibility_and_more"),
        ("transactions", "0009_escrowtransaction_selected_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userrating",
            unique_together={("from_user", "to_user", "transaction")},
        ),
    ]
