# Generated by Django 5.1.7 on 2025-04-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="temp_profile_picture_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
