# Generated by Django 5.1.7 on 2025-05-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("UNVERIFIED", "Unverified"),
                    ("PENDING", "Pending"),
                    ("VERIFIED", "Verified"),
                ],
                default="UNVERIFIED",
                max_length=10,
            ),
        ),
    ]
