# Generated by Django 5.1.7 on 2026-07-18 14:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_delete_sellerreview"),
    ]

    operations = [
        migrations.CreateModel(
            name="SellerPaymentProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bank_name",
                    models.CharField(
                        help_text="Name of the settlement bank", max_length=100
                    ),
                ),
                (
                    "bank_code",
                    models.CharField(
                        help_text="Bank code for transfer routing", max_length=10
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        help_text="NUBAN bank account number", max_length=20
                    ),
                ),
                (
                    "account_name",
                    models.CharField(
                        help_text="Verified bank account name", max_length=150
                    ),
                ),
                (
                    "paystack_subaccount_code",
                    models.CharField(
                        blank=True,
                        help_text="Paystack subaccount code for split payouts",
                        max_length=50,
                    ),
                ),
                (
                    "paystack_recipient_code",
                    models.CharField(
                        blank=True,
                        help_text="Paystack transfer recipient code for direct payouts",
                        max_length=50,
                    ),
                ),
                (
                    "bvn_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the BVN matches the account details",
                    ),
                ),
                (
                    "nin_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the National Identity Number is verified",
                    ),
                ),
                (
                    "kyc_status",
                    models.CharField(
                        choices=[
                            ("unverified", "Unverified"),
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("failed", "Failed"),
                        ],
                        default="unverified",
                        help_text="Current status of KYC/identity verification",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The user this payment profile belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Seller Payment Profile",
                "verbose_name_plural": "Seller Payment Profiles",
                "db_table": "seller_payment_profiles",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="seller_paym_user_id_8c1723_idx"
                    ),
                    models.Index(
                        fields=["kyc_status"], name="seller_paym_kyc_sta_1b2497_idx"
                    ),
                ],
            },
        ),
    ]
