services:
  redis:
    image: redis:alpine
    network_mode: service:db
    volumes:
      - redis-data:/data

  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces:cached
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=safetrade.settings.dev
      - DJANGO_ENV=development
      - DEBUG=True
      - REDIS_URL=redis://localhost:6379
      - CELERY_BROKER_URL=redis://localhost:6379
      - CELERY_RESULT_BACKEND=redis://localhost:6379
      - POSTGRES_HOST=db
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    command: sleep infinity
    network_mode: service:db

  celery_worker_default:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces:cached
    working_dir: /workspaces
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=safetrade.settings.dev
      - DJANGO_ENV=development
      - DEBUG=True
      - REDIS_URL=redis://localhost:6379
      - CELERY_BROKER_URL=redis://localhost:6379
      - CELERY_RESULT_BACKEND=redis://localhost:6379
      - POSTGRES_HOST=db
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - redis
      - db
    network_mode: service:db
    command: poetry run worker_default

  celery_beat:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces:cached
    working_dir: /workspaces
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=safetrade.settings.dev
      - DJANGO_ENV=development
      - DEBUG=True
      - REDIS_URL=redis://localhost:6379
      - CELERY_BROKER_URL=redis://localhost:6379
      - CELERY_RESULT_BACKEND=redis://localhost:6379
      - POSTGRES_HOST=db
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - redis
      - db
    network_mode: service:db
    command: poetry run beat

  celery_flower:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces:cached
    working_dir: /workspaces
    environment:
      - DJANGO_SETTINGS_MODULE=safetrade.settings.dev
      - DJANGO_ENV=development
      - DEBUG=True
      - REDIS_URL=redis://localhost:6379
      - CELERY_BROKER_URL=redis://localhost:6379
      - CELERY_RESULT_BACKEND=redis://localhost:6379
      - POSTGRES_HOST=db
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - redis
      - db
    network_mode: service:db
    command: poetry run flower

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data-1:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
      - "8000:8000"

volumes:
  postgres-data-1:
  redis-data:
