# Generated by Django 5.1.7 on 2025-06-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_breadcrumb", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breadcrumb",
            name="object_id",
            field=models.CharField(max_length=255),
        ),
    ]
