# Generated by Django 5.1.7 on 2025-06-04 21:01

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductCondition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("slug", models.SlugField(max_length=60, unique=True)),
                (
                    "quality_score",
                    models.PositiveSmallIntegerField(
                        default=10,
                        help_text="Quality score from 1 (poor) to 10 (perfect)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "price_factor",
                    models.DecimalField(
                        decimal_places=3,
                        default=1.0,
                        help_text="Price adjustment factor (0.1 to 2.0)",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(2.0),
                        ],
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                (
                    "color_code",
                    models.CharField(
                        default="#28a745",
                        help_text="Hex color code for UI display",
                        max_length=7,
                    ),
                ),
                (
                    "icon_name",
                    models.CharField(
                        blank=True,
                        help_text="Icon name for UI (e.g., 'star', 'check-circle')",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "Product Condition",
                "verbose_name_plural": "Product Conditions",
                "db_table": "product_product_conditions",
                "ordering": ["display_order", "name"],
            },
        ),
    ]
