# Generated by Django 5.1.7 on 2025-06-07 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product_condition", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="productcondition",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_conditions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="productcondition",
            index=models.Index(
                fields=["is_active", "display_order"],
                name="product_pro_is_acti_881e8d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productcondition",
            index=models.Index(
                fields=["quality_score"], name="product_pro_quality_876973_idx"
            ),
        ),
    ]
