# Generated by Django 5.1.7 on 2025-06-04 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product_base", "0004_initial"),
        ("product_rating", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="productrating",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="productratingaggregate",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rating_aggregate",
                to="product_base.product",
            ),
        ),
        migrations.AddField(
            model_name="ratinghelpfulness",
            name="rating",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="helpfulness_votes",
                to="product_rating.productrating",
            ),
        ),
        migrations.AddField(
            model_name="ratinghelpfulness",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="productrating",
            index=models.Index(
                fields=["product", "is_approved", "-created_at"],
                name="product_rat_product_6a7d75_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productrating",
            index=models.Index(
                fields=["rating", "is_approved"], name="product_rat_rating_dd06d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productrating",
            index=models.Index(
                fields=["is_verified_purchase", "is_approved"],
                name="product_rat_is_veri_b0bd31_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productrating",
            index=models.Index(
                fields=["-helpful_count", "is_approved"],
                name="product_rat_helpful_80b6b2_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productrating",
            unique_together={("product", "user")},
        ),
        migrations.AddIndex(
            model_name="productratingaggregate",
            index=models.Index(
                fields=["-average_rating", "total_count"],
                name="product_rat_average_8a1593_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ratinghelpfulness",
            unique_together={("rating", "user")},
        ),
    ]
