# Generated by Django 5.1.7 on 2025-06-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_rating", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productrating",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
