# Generated by Django 5.1.7 on 2025-06-04 21:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InventoryTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("ADD", "Add to Total"),
                            ("ACTIVATE", "Move to Available"),
                            ("ESCROW", "Place in Escrow"),
                            ("COMPLETE", "Complete Transaction"),
                            ("CANCEL", "Cancel Escrow"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("previous_total", models.IntegerField()),
                ("previous_available", models.IntegerField()),
                ("previous_in_escrow", models.IntegerField()),
                ("new_total", models.IntegerField()),
                ("new_available", models.IntegerField()),
                ("new_in_escrow", models.IntegerField()),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Inventory Transactions",
                "db_table": "product_inventory_transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
