# Generated by Django 5.1.7 on 2025-06-22 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_inventory", "0002_initial"),
        (
            "product_variant",
            "0002_productvariantimage_productvariant_cost_price_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorytransaction",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_transactions",
                to="product_variant.productvariant",
            ),
        ),
    ]
