# Generated by Django 5.1.7 on 2025-06-07 10:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dispute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("not_as_described", "Item Not As Described"),
                            ("not_received", "Item Not Received"),
                            ("damaged", "Item Damaged"),
                            ("wrong_item", "Wrong Item Received"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("opened", "Opened"),
                            ("in_review", "In Review"),
                            ("resolved_buyer", "Resolved for Buyer"),
                            ("resolved_seller", "Resolved for Seller"),
                            ("closed", "Closed"),
                        ],
                        default="opened",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispute",
                "verbose_name_plural": "Disputes",
                "db_table": "disputes",
                "ordering": ["-created_at"],
            },
        ),
    ]
