# Generated by Django 5.1.7 on 2025-07-03 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disputes", "0002_initial"),
        ("transactions", "0009_escrowtransaction_selected_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dispute",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="dispute",
            name="resolution_note",
            field=models.TextField(
                blank=True, help_text="Notes on how dispute was resolved"
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff or moderator who resolved this dispute",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_disputes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="description",
            field=models.TextField(
                help_text="Details provided by the user opening the dispute"
            ),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="opened_by",
            field=models.ForeignKey(
                help_text="User who opened this dispute",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opened_disputes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="reason",
            field=models.CharField(
                choices=[
                    ("not_as_described", "Item Not As Described"),
                    ("not_received", "Item Not Received"),
                    ("damaged", "Item Damaged"),
                    ("wrong_item", "Wrong Item Received"),
                    ("other", "Other"),
                ],
                help_text="Why the dispute was raised",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="status",
            field=models.CharField(
                choices=[
                    ("opened", "Opened"),
                    ("in_review", "In Review"),
                    ("resolved_buyer", "Resolved for Buyer"),
                    ("resolved_seller", "Resolved for Seller"),
                    ("closed", "Closed"),
                ],
                default="opened",
                help_text="Current status of the dispute",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="transaction",
            field=models.OneToOneField(
                help_text="The transaction under dispute",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dispute",
                to="transactions.escrowtransaction",
            ),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(fields=["status"], name="disputes_status_811094_idx"),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(
                fields=["opened_by"], name="disputes_opened__edb769_idx"
            ),
        ),
    ]
