# Generated by Django 5.1.7 on 2025-06-04 21:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("slug", models.SlugField(blank=True, max_length=255)),
                (
                    "short_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=200,
                        null=True,
                        unique=True,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "original_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "escrow_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("location", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("total_inventory", models.IntegerField(default=0)),
                ("available_inventory", models.IntegerField(default=0)),
                ("in_escrow_inventory", models.IntegerField(default=0)),
                ("negotiable", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("sold", "Sold"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("model", models.CharField(blank=True, max_length=100)),
                ("material", models.CharField(blank=True, max_length=100)),
                ("color", models.CharField(blank=True, max_length=50)),
                ("dimensions", models.CharField(blank=True, max_length=100)),
                ("style", models.CharField(blank=True, max_length=100)),
                ("authenticity_guaranteed", models.BooleanField(default=False)),
                ("specifications", models.JSONField(blank=True, default=dict)),
                ("features", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name_plural": "Products",
                "db_table": "product",
                "ordering": ["-created_at"],
            },
        ),
    ]
