# Generated by Django 5.1.7 on 2025-06-07 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product_base", "0002_initial"),
        ("product_condition", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="condition",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the condition of this product",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="product_condition.productcondition",
            ),
        ),
    ]
