# Generated by Django 5.1.7 on 2025-06-15 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_base", "0004_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="color",
        ),
        migrations.RemoveField(
            model_name="product",
            name="dimensions",
        ),
        migrations.RemoveField(
            model_name="product",
            name="features",
        ),
        migrations.RemoveField(
            model_name="product",
            name="material",
        ),
        migrations.RemoveField(
            model_name="product",
            name="specifications",
        ),
        migrations.RemoveField(
            model_name="product",
            name="style",
        ),
    ]
