# Generated by Django 5.1.7 on 2025-06-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "product_base",
            "0005_remove_product_color_remove_product_dimensions_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_negotiable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="max_negotiation_rounds",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="product",
            name="",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="negotiation_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="warranty_period",
            field=models.CharField(
                blank=True,
                help_text="Warranty period in months or years",
                max_length=100,
            ),
        ),
    ]
