# Generated by Django 5.1.7 on 2025-06-16 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "product_base",
            "0006_product_is_negotiable_product_max_negotiation_rounds_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="model",
        ),
        migrations.RemoveField(
            model_name="product",
            name="negotiable",
        ),
    ]
