# Generated by Django 5.1.7 on 2025-06-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_base", "0007_remove_product_model_remove_product_negotiable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
