# Generated by Django 5.1.7 on 2025-06-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_base", "0009_remove_product_available_inventory_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="require_inspection",
            new_name="requires_inspection",
        ),
        migrations.AddField(
            model_name="product",
            name="escrow_hold_period",
            field=models.PositiveIntegerField(
                default=7,
                help_text="Days to hold payment in escrow after delivery confirmation",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="requires_shipping",
            field=models.BooleanField(default=True),
        ),
    ]
