# Generated by Django 5.1.7 on 2025-06-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "product_base",
            "0010_rename_require_inspection_product_requires_inspection_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
