# Generated by Django 5.1.7 on 2025-06-26 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_base", "0011_alter_product_price"),
    ]

    operations = []
