# Generated by Django 5.1.7 on 2025-07-02 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_base", "0012_remove_product_"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="",
        ),
    ]
