# Generated by Django 5.1.7 on 2025-06-04 21:01

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NegotiationHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("price_offered", "Price Offered"),
                            ("price_accepted", "Price Accepted"),
                            ("price_rejected", "Price Rejected"),
                            ("price_countered", "Price Countered"),
                            ("price_updated", "Price Updated"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Negotiation histories",
                "db_table": "product_negotiation_history",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="PriceNegotiation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "original_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("offered_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "final_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("countered", "Countered"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("offered_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name_plural": "Negotiations",
                "db_table": "product_negotiation",
                "ordering": ["-offered_at"],
            },
        ),
    ]
