# Generated by Django 5.1.7 on 2025-06-26 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_negotiation", "0002_initial"),
        ("product_variant", "0004_remove_productvariant_escrow_hold_period_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricenegotiation",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variant_negotiations",
                to="product_variant.productvariant",
            ),
        ),
    ]
