name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    name: Code Validation
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: safetrade.test_settings
      DJANGO_SECRET_KEY: "django-insecure-wlgjuo53y49%-4y5(!%ksylle_ud%b=7%__@9hh+@$d%_^y3s!"
      DATABASE_URL: "sqlite:///:memory:"
      REDIS_URL: "redis://localhost:6379/1"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry==1.8.4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "poetry"

      - name: Install Dependencies
        run: |
          poetry config virtualenvs.in-project true
          poetry install --no-interaction

      - name: Check Poetry Lock Consistency
        run: poetry check --lock

      - name: Check for Missing Migrations
        run: poetry run python manage.py makemigrations --check --dry-run

  test:
    name: Run Test Suite
    needs: validate
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options:
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DEBUG: "True"
      DJANGO_SETTINGS_MODULE: safetrade.test_settings
      DJANGO_SECRET_KEY: django-insecure-wlgjuo53y49%-4y5(!%ksylle_ud%b=7%__@9hh+@$d%_^y3s!
      CORS_ALLOWED_ORIGINS: "http://localhost:3000"
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
      REDIS_URL: redis://localhost:6379/1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry==1.8.4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "poetry"

      - name: Install Dependencies
        run: |
          poetry config virtualenvs.in-project true
          poetry install --no-interaction

      - name: Run Pytest
        run: poetry run pytest
